### ISSUE TITLE
Email validation is wrong

### ISSUE THREAD

**Issue by nightsh** [tenders-exposed/elvis-ember#274] opened 2017-07-31 09:07 UTC
It seems our email validation (frontend based) fails to recognize perfectly valid addresses. See the image:

![image](https://user-images.githubusercontent.com/1579997/28770630-91220b2c-75e8-11e7-9a25-f259836a9a4e.png)

**Comment by zufanka** [comment] 2017-11-19 22:29
@ca1yps0 could you please pick this up?
It's a very old issue

**Comment by victor-nitu** [comment] 2017-11-21 10:22
I cannot reproduce it anymore. Closing.

**Closed by victor-nitu** 2017-11-21 10:22 UTC
Labels: bug
