### ISSUE TITLE
Can't access "My projects" page

### ISSUE THREAD

**Issue by georgiana-b** [tenders-exposed/elvis-ember#287] opened 2017-09-05 11:09 UTC
I'm on landing page, I log in then I go to "My projects" and a loader with "Loading network" appears and stays there even though the answer from server is 200 with the payload:

```json
{
  "networks": [
    {
      "id": "591d72732dcb565324000006",
      "name": null,
      "description": null,
      "user_id": "591d710b2dcb565324000005",
      "query": {
        "countries": [
          "UK"
        ],
        "cpvs": [
          "19640000"
        ],
        "years": [
          2001,
          2002,
          2003,
          2004,
          2005,
          2006,
          2007,
          2008,
          2009,
          2010,
          2011
        ]
      },
      "options": {
        "nodes": "count",
        "edges": "count"
      }
    },
   {...}
  ]
}
```

In the console I see the error: `TypeError: Cannot read property 'length' of undefined`

Browser: Chromium Version 60.0.3112.113 (openSUSE Build) (64-bit)

**Comment by chutko** [comment] 2017-09-06 09:48
in my browser (latest Chrome), My Projects are displaying correctly but if i try to load a project the whole thing freezes

**Comment by zufanka** [comment] 2017-10-06 16:32
And sometimes the edges disappear

https://elvis-ember-staging.herokuapp.com/network/59d7a9e92dcb561fd500002f , including the side panel

**Comment by zufanka** [comment] 2017-10-11 13:17
@georgiana-b do you still have the original issue? There are some more issues with the saved networks, I suggest we open a new one with proper details if this one is solved?

**Comment by georgiana-b** [comment] 2017-10-11 14:34
Yes. I still see only "Loading Network" when I go to "My project page".

**Comment by zufanka** [comment] 2017-10-11 14:38
@nightsh @ca1yps0 ?

**Comment by victor-nitu** [comment] 2017-10-24 00:38
@georgiana-b I cannot reproduce it in my env. Can you please confirm it again (one last time)? Thanks!
p.s. feel free to close this if it's fixed

**Comment by georgiana-b** [comment] 2017-10-24 07:12
Still happens for me on production, staging and develop.

**Comment by victor-nitu** [comment] 2017-10-24 07:57
Closing as a duplicate of #307

**Closed by victor-nitu** 2017-10-24 07:57 UTC
Labels: bug, priority
